version: "3"
services:
  ## MoChat (建议详细阅读1、2、3、4)
  mochat:
    build:
      context: ./
      args:
        ## 1、项目环境 - 开发环境时改为dev
        APP_ENV: production
    container_name: mochat
    ## 2、端口映射 - 开发环境时去掉注释，并修改宿主机相应的端口
    ports:
      - "9501:9501"
    #      - "9502:9502"
    #      - "9503:9503"
    volumes:
      ## 3、项目挂载 - 开发环境时去掉注释
#      - ./:/opt/www/:rw
      ## 4、日志挂载 - 开发环境时删除或注释掉
    - /var/log/docker/mochat:/var/www-log/:rw
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    networks:
      - default
networks:
  default:
